env:
  browser: true
  es2021: true
extends:
  - 'plugin:eslint-comments/recommended'
  - 'plugin:promise/recommended'
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - eslint-comments
  - promise
  - react
  - prettier
rules:
  prettier/prettier: 'error'